package demo;

import org.joda.time.LocalTime;

public class App {
  public static String getGreeting() {
      return "Hello World!";
  }

  public static void main(String[] args) {
    LocalTime currentTime = new LocalTime();
    System.out.println("The current local time is: " + currentTime);

    System.out.println(getGreeting());
  }
}

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package demo;
// 
// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }
// 
//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }
