CXX=g++ 
CXXFLAGS=-g -std=c++11

all: tlist0 tlist1

tlist0:
	$(CXX) $(CXXFLAGS) tests/$@.cpp -o build/$@


tlist1:
	$(CXX) $(CXXFLAGS) tests/$@.cpp -o build/$@


tvector:
	$(CXX) $(CXXFLAGS) tests/$@.cpp -o build/$@


tvector1:
	$(CXX) $(CXXFLAGS) tests/$@.cpp -o build/$@

tvector2:
	$(CXX) $(CXXFLAGS) tests/$@.cpp -o build/$@


clean:
	rm build/*
